//#define PARAM_HAVE_SYS_QUEUE
//#define PARAM_LIST_DYNAMIC 0
//#define PARAM_LIST_POOL 0
//#define PARAM_HAVE_SCHEDULER 0
//#define PARAM_HAVE_COMMANDS 0
#define PARAM_VMEM_64_BITS_API 1
#define MPACK_FLOAT 1
//#define MPACK_STDIO 0
